suspect code
This code appears to have NCEPLIBS library code in.
Some linear algerbra that should probably be replaced by library calls
Some time utilities that are probably available already elsewhere in DART

Does not compile:
Error: IF clause at (1) requires a scalar LOGICAL expression
also non standard:
Warning: Legacy Extension: Comma before i/o item list at (1)